export const CHANDRAPUR_TALUKAS = [
  { id: 'Warora', nameMr: 'वरोरा', nameEn: 'Warora' },
  { id: 'Rajura', nameMr: 'राजुरा', nameEn: 'Rajura' },
  { id: 'Chandrapur', nameMr: 'चंद्रपूर', nameEn: 'Chandrapur' },
  { id: 'Mul', nameMr: 'मूल', nameEn: 'Mul' },
  { id: 'Chimur', nameMr: 'चिमूर', nameEn: 'Chimur' },
  { id: 'Ballarpur', nameMr: 'बल्लारपूर', nameEn: 'Ballarpur' },
  { id: 'Bhadravati', nameMr: 'भद्रावती', nameEn: 'Bhadravati' },
  { id: 'Sindewahi', nameMr: 'सिंदेवाही', nameEn: 'Sindewahi' },
  { id: 'Brahmapuri', nameMr: 'ब्रह्मपुरी', nameEn: 'Brahmapuri' },
  { id: 'Nagbhid', nameMr: 'नागभीड', nameEn: 'Nagbhid' },
  { id: 'Gondpipri', nameMr: 'गोंडपिपरी', nameEn: 'Gondpipri' },
  { id: 'Korpana', nameMr: 'कोरपना', nameEn: 'Korpana' },
  { id: 'Pombhurna', nameMr: 'पोंभुर्णा', nameEn: 'Pombhurna' },
  { id: 'Saoli', nameMr: 'सावली', nameEn: 'Saoli' },
  { id: 'Jivati', nameMr: 'जिवती', nameEn: 'Jivati' },
];

export const TENURE_CLASSES = {
  BHOGVATDAR_CLASS_1: {
    labelMr: 'भोगवटादार वर्ग-१',
    labelEn: 'Class-1 (Freehold)',
    description: 'पूर्ण अधिकार, विनापरवानगी विक्री व वाटप अनुज्ञेय',
    badgeClass: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  },
  BHOGVATDAR_CLASS_2: {
    labelMr: 'भोगवटादार वर्ग-२',
    labelEn: 'Class-2 (Restricted)',
    description: 'शर्तयुक्त धारणाधिकार, हस्तांतरणास जिल्हाधिकारी/SDO पूर्वपरवानगी अनिवार्य',
    badgeClass: 'bg-amber-50 text-amber-700 border-amber-200',
  },
  SARKAR_SHASAN: {
    labelMr: 'शासकीय / शासन',
    labelEn: 'Government (Sarkar)',
    description: 'महाराष्ट्र शासनाकडे निहित (गायराण, नदीपात्र, सार्वजनिक प्रयोजन)',
    badgeClass: 'bg-blue-50 text-blue-700 border-blue-200',
  },
  DEVASTHAN_INAM: {
    labelMr: 'देवस्थान / इनाम',
    labelEn: 'Devasthan / Inam',
    description: 'धार्मिक न्यास किंवा सेवा इनाम जमीन, हस्तांतरणास प्रतिबंध',
    badgeClass: 'bg-purple-50 text-purple-700 border-purple-200',
  },
  FOREST_JANGAL: {
    labelMr: 'वन जमीन',
    labelEn: 'Forest Land',
    description: 'राखीव व संरक्षित वनजमीन',
    badgeClass: 'bg-green-50 text-green-800 border-green-300',
  },
};

export const VIOLATION_TYPES = {
  SHARTBHANG: {
    labelMr: 'शर्तभंग',
    labelEn: 'Breach of Allotment Conditions',
    badgeClass: 'bg-rose-50 text-rose-700 border-rose-200',
  },
  TRIBAL_LAND_VIOLATION: {
    labelMr: 'आदिवासी जमीन हस्तांतरण (कलम ३६/३६अ)',
    labelEn: 'Tribal Land Transfer (Sec 36/36A)',
    badgeClass: 'bg-red-50 text-red-700 border-red-200',
  },
  UNAUTHORIZED_NA_CONVERSION: {
    labelMr: 'विनापरवानगी अ.कृ. वापर',
    labelEn: 'Unauthorized Non-Agricultural Use',
    badgeClass: 'bg-orange-50 text-orange-700 border-orange-200',
  },
  ENCROACHMENT: {
    labelMr: 'गायराण/शासकीय जमिनीवर अतिक्रमण',
    labelEn: 'Encroachment on Govt Land (Sec 50-54)',
    badgeClass: 'bg-amber-50 text-amber-800 border-amber-200',
  },
  POKALIST_NONDI: {
    labelMr: 'पोकळीस्त नोंदी',
    labelEn: 'Defunct Hollow Mutation Remarks',
    badgeClass: 'bg-yellow-50 text-yellow-800 border-yellow-200',
  },
  GOVERNMENT_NAME_MISSING: {
    labelMr: 'शासकीय नाव वगळणे / परस्पर बदल',
    labelEn: 'Altered from Shasan to Private',
    badgeClass: 'bg-slate-50 text-slate-800 border-slate-300',
  },
};

export const ENFORCEMENT_STATUSES = {
  FLAGGED_IN_AUDIT: {
    labelMr: 'लेखापरीक्षणात नोंद',
    labelEn: 'Audit Flagged',
    color: 'bg-slate-100 text-slate-700 border-slate-200',
  },
  FIELD_PANCHNAMA_COMPLETED: {
    labelMr: 'स्थळ पंचनामा पूर्ण',
    labelEn: 'Panchnama Done',
    color: 'bg-blue-50 text-blue-700 border-blue-200',
  },
  NOTICE_ISSUED: {
    labelMr: 'कारणे दाखवा नोटीस बजावली',
    labelEn: 'Notice Issued',
    color: 'bg-amber-50 text-amber-700 border-amber-200',
  },
  HEARING_SCHEDULED: {
    labelMr: 'सुनावणी सुरू',
    labelEn: 'Hearing Scheduled',
    color: 'bg-indigo-50 text-indigo-700 border-indigo-200',
  },
  FINAL_ORDER_PASSED: {
    labelMr: 'अंतिम आदेश पारित',
    labelEn: 'Final Order Passed',
    color: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  },
  RECTIFIED_7_12: {
    labelMr: '७/१२ दुरुस्ती प्रमाणित',
    labelEn: '7/12 Rectified',
    color: 'bg-teal-50 text-teal-700 border-teal-200',
  },
  DISMISSED: {
    labelMr: 'प्रकरण निकाली / फेटाळले',
    labelEn: 'Dismissed',
    color: 'bg-gray-100 text-gray-600 border-gray-200',
  },
};

export const DMS_DOC_TYPES = {
  OLD_7_12_ARCHIVE: {
    labelMr: 'सन १९५० जुना सातबारा उतारा',
    labelEn: '1950 Baseline 7/12 Extract',
    iconName: 'FileArchive',
  },
  FERFAR_REGISTER_COPY: {
    labelMr: 'गाव नमुना ६ फेरफार प्रत',
    labelEn: 'Village Form VI Mutation Extract',
    iconName: 'FileSpreadsheet',
  },
  FIELD_PANCHNAMA: {
    labelMr: 'स्थळ पंचनामा व तपासणी अहवाल',
    labelEn: 'Field Panchnama Report',
    iconName: 'ClipboardCheck',
  },
  SDO_ORDER: {
    labelMr: 'उपविभागीय अधिकारी (SDO) आदेश',
    labelEn: 'SDO Quasi-Judicial Order',
    iconName: 'Scale',
  },
  COLLECTOR_ORDER: {
    labelMr: 'जिल्हाधिकारी शासन जमा आदेश',
    labelEn: 'Collector Resumption Order',
    iconName: 'Landmark',
  },
  SHOW_CAUSE_NOTICE: {
    labelMr: 'कारणे दाखवा नोटीस',
    labelEn: 'Show-Cause Legal Notice',
    iconName: 'MailWarning',
  },
};

export const REVENUE_GLOSSARY_CATEGORIES = [
  { id: 'ALL', labelMr: 'सर्व संज्ञा', labelEn: 'All Terms' },
  { id: 'VIOLATION', labelMr: 'शर्तभंग व उल्लंघन', labelEn: 'Violations & Enforcement' },
  { id: 'LAND_CLASS', labelMr: 'जमिनीचा प्रकार व मोजणी', labelEn: 'Land Class & Survey' },
  { id: 'DEED', labelMr: 'खरेदी-विक्री व दस्त', labelEn: 'Deeds & Transactions' },
  { id: 'MUTATION', labelMr: 'वारस व फेरफार', labelEn: 'Mutations & Succession' },
  { id: 'RIGHTS', labelMr: 'इतर हक्क व बोजा', labelEn: 'Rights & Encumbrances' },
  { id: 'AUTHORITY', labelMr: 'महसूल अधिकारी', labelEn: 'Revenue Authorities' },
  { id: 'AREA_TAX', labelMr: 'क्षेत्र व आकारणी', labelEn: 'Area & Tax Units' },
];

export const REVENUE_SHORTCUTS = [
  {
    shortcut: 'विनापरवानगी अ.कृ. वापर',
    fullFormMr: 'विनापरवानगी अकृषिक वापर',
    fullFormEn: 'Unauthorized Non-Agricultural (NA) Use',
    category: 'VIOLATION',
    mlrcSection: 'कलम ४२, ४४, ४५ व ४७ (MLRC 1966)',
    severity: 'CRITICAL',
    descriptionMr:
      'सक्षम महसूल प्राधिकाऱ्यांच्या (जिल्हाधिकारी / उपविभागीय अधिकारी) पूर्वपरवानगीशिवाय कृषी जमिनीचा निवासी, व्यावसायिक अथवा औद्योगिक कारणासाठी केलेला अनधिकृत वापर. ७/१२ च्या इतर हक्कात ही नोंद आल्यास चालू आकारणीच्या २५ पट दंड, दंडात्मक अकृषिक आकारणी किंवा शासन जमाची वैधानिक कारवाई होऊ शकते.',
    descriptionEn:
      'Utilization of agricultural land for residential, commercial, or industrial purposes without obtaining prior statutory non-agricultural (NA) permission under MLRC 1966. Attracts compounding penalties, unauthorized NA assessment, and resumption (Shasan Jama) proceedings.',
  },
  {
    shortcut: 'अ.कृ.',
    fullFormMr: 'अकृषिक',
    fullFormEn: 'Non-Agricultural (NA)',
    category: 'LAND_CLASS',
    mlrcSection: 'कलम ४२ ते ४४',
    severity: 'STANDARD',
    descriptionMr: 'शेतीव्यतिरिक्त इतर प्रयोजनासाठी (उदा. घरबांधणी, कारखाना, दुकान) अधिकृतपणे रूपांतरित झालेली जमीन.',
    descriptionEn: 'Land legally converted from agricultural to non-agricultural purpose with statutory Collector sanction.',
  },
  {
    shortcut: 'कृ.',
    fullFormMr: 'कृषिक',
    fullFormEn: 'Agricultural',
    category: 'LAND_CLASS',
    mlrcSection: 'कलम ४१',
    severity: 'STANDARD',
    descriptionMr: 'केवळ शेती, फलोत्पादन किंवा दुग्धव्यवसायासाठी वापरली जाणारी मूळ जमीन.',
    descriptionEn: 'Original parcel zoned and designated exclusively for agricultural and allied farming activities.',
  },
  {
    shortcut: 'भो.व. १',
    fullFormMr: 'भोगवटादार वर्ग-१',
    fullFormEn: 'Occupant Class-1 (Freehold)',
    category: 'LAND_CLASS',
    mlrcSection: 'कलम २९(२)',
    severity: 'STANDARD',
    descriptionMr: 'पूर्ण मालकी हक्क असलेली जमीन. विक्री, हस्तांतरण, गहाण किंवा वाटपासाठी शासनाच्या पूर्वपरवानगीची आवश्यकता नसते.',
    descriptionEn: 'Absolute freehold tenure without statutory restrictions on alienation, transfer, or partition.',
  },
  {
    shortcut: 'भो.व. २',
    fullFormMr: 'भोगवटादार वर्ग-२',
    fullFormEn: 'Occupant Class-2 (Restricted)',
    category: 'LAND_CLASS',
    mlrcSection: 'कलम २९(३)',
    severity: 'RESTRICTED',
    descriptionMr: 'शर्तयुक्त / मर्यादित धारणाधिकार असलेली जमीन (शासनाने वाटप केलेली, सिलिंग किंवा कुळकायद्यातील जमीन). हस्तांतरणास जिल्हाधिकारी किंवा SDO यांची पूर्वपरवानगी बंधनकारक असते.',
    descriptionEn: 'Conditional or restricted tenure (allotted by govt, ceiling surplus, or tenancy grant). Alienation or NA requires prior Collector sanction; breach constitutes Shartbhang.',
  },
  {
    shortcut: 'शा.प.',
    fullFormMr: 'शासकीय पट्टा',
    fullFormEn: 'Government Lease',
    category: 'LAND_CLASS',
    mlrcSection: 'कलम ३८',
    severity: 'RESTRICTED',
    descriptionMr: 'विशिष्ट मुदतीसाठी शासनाने करारावर भाडेपट्ट्याने दिलेली जमीन. मुदत संपल्यावर किंवा अटींचे उल्लंघन झाल्यास शासन जमा होते.',
    descriptionEn: 'Land held under a defined lease term directly from the State Government under prescribed conditions.',
  },
  {
    shortcut: 'स.नं.',
    fullFormMr: 'सर्व्हे नंबर',
    fullFormEn: 'Survey Number',
    category: 'LAND_CLASS',
    mlrcSection: 'कलम ७९ ते ८८',
    severity: 'STANDARD',
    descriptionMr: 'भूमी अभिलेख विभागाने मूळ मोजणीच्या वेळी जमिनीला दिलेला विशिष्ट ओळख क्रमांक.',
    descriptionEn: 'Original cadastral survey number assigned by the Department of Land Records during initial settlement.',
  },
  {
    shortcut: 'ग.नं.',
    fullFormMr: 'गट नंबर',
    fullFormEn: 'Gat / Group Number',
    category: 'LAND_CLASS',
    mlrcSection: 'जमीन एकत्रीकरण कायदा',
    severity: 'STANDARD',
    descriptionMr: 'तुकडेबंदी व जमीन एकत्रीकरण योजनेअंतर्गत अनेक लहान सर्व्हे नंबर एकत्र करून दिलेला गट क्रमांक.',
    descriptionEn: 'Consolidated parcel identifier created by grouping historical survey numbers under consolidation schemes.',
  },
  {
    shortcut: 'हि.नं.',
    fullFormMr: 'हिस्सा नंबर',
    fullFormEn: 'Sub-division (Hissa) Number',
    category: 'LAND_CLASS',
    mlrcSection: 'कलम ८५',
    severity: 'STANDARD',
    descriptionMr: 'एकाच सर्व्हे अथवा गट नंबरमधील अधिकृतपणे विभागलेला पोटभाग क्रमांक.',
    descriptionEn: 'Legally surveyed sub-division within an existing survey or gat number.',
  },
  {
    shortcut: 'पो.ख.',
    fullFormMr: 'पोटखराब जमीन',
    fullFormEn: 'Uncultivable / Waste Land',
    category: 'AREA_TAX',
    mlrcSection: 'नियम ३ (जमीन महसूल नियम)',
    severity: 'STANDARD',
    descriptionMr: 'गटातील नापीक, नाला, खडक अथवा रस्त्याखालील क्षेत्र ज्यावर शेती महसूल आकारला जात नाही (वर्ग अ: नैसर्गिक नापीक, वर्ग ब: सार्वजनिक वापरासाठी राखीव).',
    descriptionEn: 'Uncultivable area within a parcel (Class A: uncultivable due to rocks/streams; Class B: assigned for public roads, paths, or tanks). No assessment is levied.',
  },
  {
    shortcut: 'ख.ख. / ख.दे.',
    fullFormMr: 'खरेदीखत / खरेदी देणे',
    fullFormEn: 'Sale Deed / Conveyance',
    category: 'DEED',
    mlrcSection: 'नोंदणी कायदा कलम १७',
    severity: 'STANDARD',
    descriptionMr: 'जमिनीची कायदेशीर विक्री दर्शवणारा दुय्यम निबंधक कार्यालयातील अधिकृत नोंदणीकृत दस्त.',
    descriptionEn: 'Registered sale deed evidencing lawful monetary transfer of land ownership from seller to purchaser.',
  },
  {
    shortcut: 'ब.प. / ब.दे.',
    fullFormMr: 'बक्षीसपत्र / बक्षीस देणे',
    fullFormEn: 'Gift Deed',
    category: 'DEED',
    mlrcSection: 'मालमत्ता हस्तांतरण कायदा कलम १२२',
    severity: 'STANDARD',
    descriptionMr: 'कोणताही आर्थिक मोबदला न घेता प्रेमापोटी किंवा नात्यामध्ये नोंदणीकृत दस्ताद्वारे दिलेली जमीन.',
    descriptionEn: 'Voluntary gratuitous conveyance of land made without monetary consideration.',
  },
  {
    shortcut: 'ह.सो.प.',
    fullFormMr: 'हक्कसोडपत्र',
    fullFormEn: 'Release / Relinquishment Deed',
    category: 'DEED',
    mlrcSection: 'नोंदणी कायदा',
    severity: 'STANDARD',
    descriptionMr: 'सामाईक किंवा वारसा हक्कातील सहहिस्सेदाराने स्वतःचा हिस्सा इतर सहहिस्सेदारांच्या बाजूने स्वेच्छेने सोडून दिल्याचा नोंदणीकृत दस्त.',
    descriptionEn: 'Registered deed whereby a co-owner or legal heir surrenders and extinguishes their legal share in favor of other co-sharers.',
  },
  {
    shortcut: 'वा.प.',
    fullFormMr: 'वाटपपत्र',
    fullFormEn: 'Partition Deed',
    category: 'DEED',
    mlrcSection: 'कलम ८५ (MLRC)',
    severity: 'STANDARD',
    descriptionMr: 'एकत्र कुटुंबातील किंवा सामाईक धारकांमधील जमिनीची कायदेशीर वाटणी करून प्रत्येकाचा स्वतंत्र हिस्सा दर्शवणारा दस्त.',
    descriptionEn: 'Statutory or registered partition of joint family or co-owned land defining individual separate boundaries.',
  },
  {
    shortcut: 'सा.ख.',
    fullFormMr: 'साठेखत',
    fullFormEn: 'Agreement to Sale',
    category: 'DEED',
    mlrcSection: 'कलम ५४ (मालमत्ता हस्तांतरण)',
    severity: 'STANDARD',
    descriptionMr: 'भविष्यात खरेदीखत करण्याचे आश्वासन देणारा करारनामा (हा अंतिम मालकी हक्क निर्माण करत नाही).',
    descriptionEn: 'Executory agreement embodying terms of future sale. Does not convey proprietary title by itself.',
  },
  {
    shortcut: 'मु.प.',
    fullFormMr: 'मुखत्यारपत्र',
    fullFormEn: 'Power of Attorney (PoA)',
    category: 'DEED',
    mlrcSection: 'मुखत्यारपत्र कायदा १८८२',
    severity: 'STANDARD',
    descriptionMr: 'जमीन मालकाने स्वतःच्या वतीने व्यवस्था किंवा व्यवहार करण्यासाठी दुसऱ्या व्यक्तीस दिलेला कायदेशीर अधिकार.',
    descriptionEn: 'Legal authorization given by a landowner to another individual to act and manage proceedings on their behalf.',
  },
  {
    shortcut: 'मृ.प.',
    fullFormMr: 'मृत्युपत्र / इच्छापत्र',
    fullFormEn: 'Will / Testament',
    category: 'DEED',
    mlrcSection: 'भारतीय वारसा कायदा',
    severity: 'STANDARD',
    descriptionMr: 'व्यक्तीने मृत्यूनंतर आपल्या जमिनीची विल्हेवाट कशी लावावी याविषयी लिहून ठेवलेला कायदेशीर दस्त.',
    descriptionEn: 'Testamentary disposition outlining how land ownership shall devolve upon the testator’s death.',
  },
  {
    shortcut: 'गहाण.ख.',
    fullFormMr: 'गहाणखत',
    fullFormEn: 'Mortgage Deed',
    category: 'DEED',
    mlrcSection: 'कलम ५८ (मालमत्ता हस्तांतरण)',
    severity: 'ENCUMBRANCE',
    descriptionMr: 'कर्ज किंवा पत सुरक्षिततेसाठी बँकेकडे अथवा वित्तीय संस्थेकडे जमीन गहाण ठेवल्याचा अधिकृत दस्त.',
    descriptionEn: 'Registered instrument creating a legal security charge over the parcel for securing bank debt or credit.',
  },
  {
    shortcut: 'फे.नं.',
    fullFormMr: 'फेरफार नंबर',
    fullFormEn: 'Mutation Entry Number',
    category: 'MUTATION',
    mlrcSection: 'कलम १४८ ते १५० (गाव नमुना ६)',
    severity: 'STANDARD',
    descriptionMr: '७/१२ वरील मालकी, हक्क किंवा भोगवट्यात झालेला कोणताही बदल नोंदवणारा गाव नमुना ६ मधील अधिकृत अनुक्रमांक.',
    descriptionEn: 'Sequential entry in Village Form VI recording any alteration, transfer, inheritance, or encumbrance affecting the 7/12 record.',
  },
  {
    shortcut: 'मृ.नों. / म.नों.',
    fullFormMr: 'मयत नोंद / मृत्यू नोंद',
    fullFormEn: 'Death Mutation Entry',
    category: 'MUTATION',
    mlrcSection: 'कलम १४९',
    severity: 'STANDARD',
    descriptionMr: 'जमीन धारकाचा मृत्यू झाल्यानंतर ७/१२ वरून त्याचे नाव कमी करण्यासाठी फेरफारमध्ये केलेली अधिकृत नोंद.',
    descriptionEn: 'Mutation entry recording the demise of the titleholder to update revenue records.',
  },
  {
    shortcut: 'वा.नों.',
    fullFormMr: 'वारस नोंद',
    fullFormEn: 'Heirship / Succession Mutation',
    category: 'MUTATION',
    mlrcSection: 'कलम १४९ व १५०',
    severity: 'STANDARD',
    descriptionMr: 'मूळ खातेदाराच्या मृत्यूनंतर कायदेशीर वारसांची नावे चौकशीअंती ७/१२ वर दाखल करण्याची फेरफार नोंद.',
    descriptionEn: 'Formal mutation recognizing and entering lawful heirs upon the 7/12 extract following local revenue inquiry.',
  },
  {
    shortcut: 'ना.वि.नों.',
    fullFormMr: 'नावात बदल नोंद',
    fullFormEn: 'Name Correction Mutation',
    category: 'MUTATION',
    mlrcSection: 'कलम १५०',
    severity: 'STANDARD',
    descriptionMr: 'खातेदाराच्या नावातील स्पेलिंग किंवा लग्नानंतर झालेल्या बदलाची राजपत्राधारे प्रमाणित नोंद.',
    descriptionEn: 'Official correction of spelling or surname change in titleholder name backed by gazette notification.',
  },
  {
    shortcut: 'द.नं.',
    fullFormMr: 'दस्त नोंदणी क्रमांक',
    fullFormEn: 'Registration Document Number',
    category: 'MUTATION',
    mlrcSection: 'नोंदणी कायदा',
    severity: 'STANDARD',
    descriptionMr: 'दुय्यम निबंधक कार्यालयात दस्तऐवज नोंदणी करताना दिलेला अधिकृत वर्षानिहाय नोंदणी क्रमांक.',
    descriptionEn: 'Unique registration serial number issued by the Sub-Registrar of Assurances upon document registration.',
  },
  {
    shortcut: 'इ.ह.',
    fullFormMr: 'इतर हक्क स्तंभ',
    fullFormEn: 'Other Rights Column (Column 12)',
    category: 'RIGHTS',
    mlrcSection: 'गाव नमुना ७/१२ नियम',
    severity: 'STANDARD',
    descriptionMr: '७/१२ उताऱ्यातील खालचा भाग, ज्यामध्ये बँकेचे कर्ज (बोजा), कुळ हक्क, कोर्ट दावा, शासकीय निर्बंध अथवा अनधिकृत वापराच्या नोंदी केल्या जातात.',
    descriptionEn: 'The lower half of the 7/12 extract where bank liens, tenant rights, court lis pendens, and restrictive revenue conditions are recorded.',
  },
  {
    shortcut: 'बो.',
    fullFormMr: 'बोजा (कर्ज प्रभार)',
    fullFormEn: 'Encumbrance / Bank Loan Charge',
    category: 'RIGHTS',
    mlrcSection: 'कलम १४८',
    severity: 'ENCUMBRANCE',
    descriptionMr: 'शेतकऱ्याने किंवा मालकाने बँकेकडून घेतलेल्या कर्जापोटी जमिनीवर चढवलेला कायदेशीर प्रभार.',
    descriptionEn: 'Financial encumbrance registered by a commercial or cooperative bank against unpaid agricultural/industrial loans.',
  },
  {
    shortcut: 'कु.का.',
    fullFormMr: 'कुलकायदा',
    fullFormEn: 'Tenancy Act (Bombay Tenancy Act 1948)',
    category: 'RIGHTS',
    mlrcSection: 'मुंबई कुळवहिवाट व शेतजमीन कायदा १९४८',
    severity: 'RESTRICTED',
    descriptionMr: 'जमीन कसणाऱ्या कुळांना संरक्षण देणारा कायदा. कलम ३२-ग किंवा ३२-म अन्वये कुळाने खरेदी केलेली जमीन पूर्वपरवानगीशिवाय विकता येत नाही.',
    descriptionEn: 'Bombay Tenancy & Agricultural Lands Act 1948 protecting protected/ordinary tenants. Imposes statutory restrictions on alienation.',
  },
  {
    shortcut: 'कु.ह.',
    fullFormMr: 'कुळ हक्क',
    fullFormEn: 'Protected Tenant Right',
    category: 'RIGHTS',
    mlrcSection: 'कलम ४ (कुळ कायदा)',
    severity: 'RESTRICTED',
    descriptionMr: 'जमिनीवर कायदेशीर कुळाचा ताबा व कसत असल्याचा हक्क दर्शवणारी ७/१२ वरील नोंद.',
    descriptionEn: 'Recognized tenancy right recorded on the 7/12 establishing cultivating possession of the tenant.',
  },
  {
    shortcut: 'दा.नं. / को.दा.',
    fullFormMr: 'दावा नंबर / न्यायालयीन दावा',
    fullFormEn: 'Court Case / Lis Pendens',
    category: 'RIGHTS',
    mlrcSection: 'कलम ५२ (मालमत्ता हस्तांतरण)',
    severity: 'CRITICAL',
    descriptionMr: 'जमिनीबाबत दिवाणी किंवा महसूल न्यायालयात खटला प्रलंबित असल्याची ७/१२ च्या इतर हक्कातील नोंद.',
    descriptionEn: 'Lis pendens notice signifying ongoing civil or revenue litigation regarding title, ownership, or boundary.',
  },
  {
    shortcut: 'अं.हु.',
    fullFormMr: 'अंमलबजावणी हुकूम',
    fullFormEn: 'Execution of Court Decree',
    category: 'RIGHTS',
    mlrcSection: 'दिवाणी प्रक्रिया संहिता आदेश २१',
    severity: 'CRITICAL',
    descriptionMr: 'न्यायालयाने दिलेल्या अंतिम हुकूमनाम्याची किंवा निकालाची महसूल अभिलेखात अंमलबजावणी करण्याचे आदेश.',
    descriptionEn: 'Execution order directing revenue authorities to enforce a civil court decree on the record of rights.',
  },
  {
    shortcut: 'जप्ती नों.',
    fullFormMr: 'जप्तीची नोंद',
    fullFormEn: 'Attachment Order / Seizure',
    category: 'RIGHTS',
    mlrcSection: 'कलम १७८ ते १८४ (MLRC)',
    severity: 'CRITICAL',
    descriptionMr: 'शासकीय थकबाकी, कर किंवा न्यायालयीन आदेशावरून जमीन जप्त केल्याची ७/१२ वरील अधिकृत नोंद.',
    descriptionEn: 'Statutory attachment of the parcel for recovery of public revenue arrears, penalties, or judicial executions.',
  },
  {
    shortcut: 'मा.जि.',
    fullFormMr: 'मा. जिल्हाधिकारी',
    fullFormEn: 'Hon. District Collector',
    category: 'AUTHORITY',
    mlrcSection: 'कलम ७ व ८ (MLRC 1966)',
    severity: 'STANDARD',
    descriptionMr: 'जिल्ह्यातील सर्वोच्च महसूल अधिकारी. भोगवटादार वर्ग-२ विक्री परवानगी, अकृषिक (NA) आदेश व शासन जमाचे अंतिम अधिकार.',
    descriptionEn: 'District Collector; supreme revenue authority exercising final powers over Class-2 alienation, NA conversion, and resumption (Shasan Jama).',
  },
  {
    shortcut: 'उ.वि.अ.',
    fullFormMr: 'उपविभागीय अधिकारी (SDO / प्रांत)',
    fullFormEn: 'Sub-Divisional Officer (SDO)',
    category: 'AUTHORITY',
    mlrcSection: 'कलम ९ व १३ (MLRC 1966)',
    severity: 'STANDARD',
    descriptionMr: 'तालुका समूहाचे प्रमुख अधिकारी. अर्ध-न्यायिक सुनावण्या, शर्तभंग तपासणी व फेरफार अपील चालवणारे सक्षम प्राधिकारी.',
    descriptionEn: 'Sub-Divisional Officer / Prant Officer heading sub-division with quasi-judicial appellate and Shartbhang jurisdiction.',
  },
  {
    shortcut: 'मा.तह.',
    fullFormMr: 'मा. तहसीलदार',
    fullFormEn: 'Hon. Tehsildar',
    category: 'AUTHORITY',
    mlrcSection: 'कलम १० (MLRC 1966)',
    severity: 'STANDARD',
    descriptionMr: 'तालुक्याचे मुख्य महसूल अधिकारी व तालुका दंडाधिकारी. अतिक्रमण निष्कासन, वारस प्रकरणे व रस्ता वाद निकाली काढणारे अधिकारी.',
    descriptionEn: 'Tehsildar; chief taluka administrative officer and taluka executive magistrate handling tenancy, succession, and encroachment removals.',
  },
  {
    shortcut: 'मं.अ.',
    fullFormMr: 'मंडळ अधिकारी',
    fullFormEn: 'Circle Officer (CO)',
    category: 'AUTHORITY',
    mlrcSection: 'कलम १२ (MLRC 1966)',
    severity: 'STANDARD',
    descriptionMr: 'अनेक गावांमधील तलाठ्यांच्या कामावर देखरेख ठेवणारे व गाव नमुना ६ मधील फेरफार नोंदी प्रमाणित (प्रमाणन) करणारे अधिकारी.',
    descriptionEn: 'Revenue Circle Officer supervising talathis and possessing statutory power to certify or reject mutation entries in Form VI.',
  },
  {
    shortcut: 'त.सा.',
    fullFormMr: 'तलाठी साहेब / पटवारी',
    fullFormEn: 'Talathi / Village Revenue Officer',
    category: 'AUTHORITY',
    mlrcSection: 'कलम १५ (MLRC 1966)',
    severity: 'STANDARD',
    descriptionMr: 'गावपातळीवरील प्राथमिक महसूल अधिकारी. गाव नमुना १ ते २१ नोंदवह्या, ७/१२ अद्ययावतीकरण व पीक पाहणी (ई-पीक पाहणी) नोंदवणारे घटक.',
    descriptionEn: 'Village revenue officer maintaining village account registers 1 through 21, preparing 7/12 extracts, and logging crop inspections.',
  },
  {
    shortcut: 'म.ज.म.',
    fullFormMr: 'महाराष्ट्र जमीन महसूल संहिता १९६६',
    fullFormEn: 'Maharashtra Land Revenue Code (MLRC) 1966',
    category: 'AUTHORITY',
    mlrcSection: 'कायदा क्र. ४१ सन १९६६',
    severity: 'STANDARD',
    descriptionMr: 'महाराष्ट्रातील सर्व जमिनीचे अधिकार, वर्गवारी, मोजणी, महसूल व फेरफार यांचे नियमन करणारा मुख्य वैधानिक कायदा.',
    descriptionEn: 'Primary legislation governing land tenure, records of rights, revenue assessment, mutations, and quasi-judicial inquiries across Maharashtra.',
  },
  {
    shortcut: 'भूसं.',
    fullFormMr: 'भूसंपादन',
    fullFormEn: 'Land Acquisition',
    category: 'AUTHORITY',
    mlrcSection: 'भूसंपादन कायदा २०१३ / MLRC',
    severity: 'RESTRICTED',
    descriptionMr: 'रस्ते, धरणे, रेल्वे अथवा सार्वजनिक प्रकल्पांसाठी शासनाने कायदेशीर मोबदला देऊन संपादित केलेली जमीन.',
    descriptionEn: 'Compulsory statutory acquisition of private land by the State for public projects upon payment of compensation.',
  },
  {
    shortcut: 'पुन.',
    fullFormMr: 'पुनर्वसन',
    fullFormEn: 'Rehabilitation & Resettlement',
    category: 'AUTHORITY',
    mlrcSection: 'महाराष्ट्र प्रकल्पबाधित व्यक्ती पुनर्वसन कायदा',
    severity: 'RESTRICTED',
    descriptionMr: 'प्रकल्पबाधित शेतकऱ्यांना शेती किंवा घरासाठी वाटप केलेली पुनर्वसित जमीन (वर्ग-२ धारणाधिकार).',
    descriptionEn: 'Land granted to project-affected persons under rehabilitation laws; governed by non-alienation conditional tenure.',
  },
  {
    shortcut: 'ना.ह.प्र.',
    fullFormMr: 'ना हरकत प्रमाणपत्र',
    fullFormEn: 'No Objection Certificate (NOC)',
    category: 'AUTHORITY',
    mlrcSection: 'प्रशासकीय नियम',
    severity: 'STANDARD',
    descriptionMr: 'जमिनीच्या खरेदी-विक्री, कर्ज अथवा अकृषिक वापरासाठी सक्षम अधिकाऱ्याने दिलेला ना-हरकत दाखला.',
    descriptionEn: 'Administrative certificate issued by competent authority declaring no objection to sale, loan, or development.',
  },
  {
    shortcut: 'हे.',
    fullFormMr: 'हेक्टर',
    fullFormEn: 'Hectare',
    category: 'AREA_TAX',
    mlrcSection: 'मोजणी नियम',
    severity: 'STANDARD',
    descriptionMr: 'जमीन मोजणीचे मुख्य मेट्रिक एकक. १ हेक्टर = १०० आर = १०,००० चौरस मीटर = २.४७ एकर.',
    descriptionEn: 'Primary metric area unit in Maharashtra land records. 1 Hectare = 100 Are = 10,000 sq. m = ~2.471 Acres.',
  },
  {
    shortcut: 'आर',
    fullFormMr: 'आर (गुंठा)',
    fullFormEn: 'Are (Guntha Equivalent)',
    category: 'AREA_TAX',
    mlrcSection: 'मोजणी नियम',
    severity: 'STANDARD',
    descriptionMr: '१ आर = १०० चौरस मीटर = १,०७६.४ चौरस फूट (महाराष्ट्रात १ आर म्हणजेच १ गुंठा धरला जातो).',
    descriptionEn: 'Metric unit equivalent to 100 square meters (1,076.4 sq. ft.). Commonly referred to as 1 Guntha in local practice.',
  },
  {
    shortcut: 'चौ.मी.',
    fullFormMr: 'चौरस मीटर',
    fullFormEn: 'Square Meter (Sq. Mtr.)',
    category: 'AREA_TAX',
    mlrcSection: 'मोजणी नियम',
    severity: 'STANDARD',
    descriptionMr: 'अकृषिक (NA) भूखंडांचे मोजमाप दर्शवणारे अचूक एकक (१ चौ.मी. = १०.७६४ चौ. फूट).',
    descriptionEn: 'Standard metric area unit especially mandatory for plotting non-agricultural sub-divisions.',
  },
  {
    shortcut: 'आ.रु.पै.',
    fullFormMr: 'आकारणी रुपये पैसे',
    fullFormEn: 'Assessment (Rupees & Paise)',
    category: 'AREA_TAX',
    mlrcSection: 'कलम ६४ ते ६८',
    severity: 'STANDARD',
    descriptionMr: 'जमिनीच्या गुणवत्तेनुसार व पिकांनुसार ठरवलेला वार्षिक शासकीय जमीन महसूल कर.',
    descriptionEn: 'Annual land revenue tax assessed by the State based on soil classification and statutory settlement rates.',
  },
  {
    shortcut: 'जु.आ.',
    fullFormMr: 'जुडी आकारणी',
    fullFormEn: 'Quit-Rent / Judi Assessment',
    category: 'AREA_TAX',
    mlrcSection: 'इनाम निर्मूलन कायदा',
    severity: 'STANDARD',
    descriptionMr: 'पूर्वीच्या इनाम जमिनींवर ब्रिटिशांनी किंवा संस्थानांनी लागू केलेली सवलतीची वार्षिक कर आकारणी.',
    descriptionEn: 'Concessional or fixed quit-rent levied on historically exempted Inam lands under Inam Abolition Acts.',
  },
  {
    shortcut: 'शर्तभंग',
    fullFormMr: 'शर्तभंग (अटींचा भंग)',
    fullFormEn: 'Breach of Allotment Conditions (Shartbhang)',
    category: 'VIOLATION',
    mlrcSection: 'कलम ३६, ३६अ, ४४ व नियम',
    severity: 'CRITICAL',
    descriptionMr: 'भोगवटादार वर्ग-२ किंवा शासकीय पट्ट्यावरील अटींचे (उदा. विनापरवानगी विक्री, विनापरवानगी अ.कृ. वापर, भाडेपट्टा) उल्लंघन.',
    descriptionEn: 'Breach of statutory covenants or grant restrictions (unapproved sale, unauthorized NA, or transfer of Class-2 land).',
  },
  {
    shortcut: 'शासन जमा',
    fullFormMr: 'शासन जमा (जमीन सरकार हस्तगत करणे)',
    fullFormEn: 'Resumption / Confiscation to State (Shasan Jama)',
    category: 'VIOLATION',
    mlrcSection: 'कलम ३६अ(३), ५०-५४ (MLRC)',
    severity: 'CRITICAL',
    descriptionMr: 'शर्तभंग, गायरान अतिक्रमण किंवा बेकायदेशीर आदिवासी जमीन हस्तांतरण सिद्ध झाल्यास जिल्हाधिकाऱ्यांनी जमीन परत शासकीय ताब्यात घेण्याचा अंतिम आदेश.',
    descriptionEn: 'Quasi-judicial order passed by the District Collector forfeiting the land and restoring ownership back to the State Government.',
  },
  {
    shortcut: 'पोकळीस्त नोंदी',
    fullFormMr: 'पोकळीस्त अनधिकृत नोंदी',
    fullFormEn: 'Defunct Hollow Mutation Remarks',
    category: 'VIOLATION',
    mlrcSection: 'महसूल परिपत्रके',
    severity: 'CRITICAL',
    descriptionMr: 'कोणत्याही अधिकृत फेरफार आदेशाशिवाय किंवा जुन्या बु.गा.दे., ता.गा.दे. अशा आधार नसलेल्या संशयास्पद नोंदी, ज्यांची चौकशी सुरू आहे.',
    descriptionEn: 'Spurious, hollow, or unverified historical mutation acronyms (e.g. Bu.Ga.De., Ta.Ga.De.) lacking primary sanction registers.',
  },
];

export const lookupRevenueShortcut = (term) => {
  if (!term) return null;
  const clean = String(term).trim().toLowerCase();
  return REVENUE_SHORTCUTS.find(
    (item) =>
      item.shortcut.toLowerCase() === clean ||
      item.fullFormMr.toLowerCase() === clean ||
      item.fullFormEn.toLowerCase() === clean ||
      clean.includes(item.shortcut.toLowerCase())
  );
};

